title: Blaaaaaagggghhh!!!
author: QrrTT
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just for Learning.
theme: minima
# social links

github_username:  QrrTT

show_excerpts: true # set to false to remove excerpts on the homepage
